### ISSUE TITLE
Error en el nombre del archivo index

### ISSUE THREAD

**Issue by cborcar637** [pperval015/Simpsons#1]
El archivo principal de cualquier sitio web debe de llamarse "index.html". Sin embargo, el archivo principal de este proyecto se llama "index" sin la extensión "html". Si no se le pone la extensión, la página web no será accesible a través de GitHub Pages.

Debería renombrarse el archivo "index" a "index.html"

**Comment by dplacor1704** [comment]
Acabo de cambiar el nombre, ya creo que está bien.
